package main
// Generated by https://quicktype.io

type Page struct {
  Kind              string            `json:"kind"`             
  URL               URL               `json:"url"`              
  Queries           Queries           `json:"queries"`          
  Context           Context           `json:"context"`          
  SearchInformation SearchInformation `json:"searchInformation"`
  Items             []Item            `json:"items"`            
}

type Context struct {
  Title string `json:"title"`
}

type Item struct {
  Kind             Kind    `json:"kind"`            
  Title            string  `json:"title"`           
  HTMLTitle        string  `json:"htmlTitle"`       
  Link             string  `json:"link"`            
  DisplayLink      string  `json:"displayLink"`     
  Snippet          string  `json:"snippet"`         
  HTMLSnippet      string  `json:"htmlSnippet"`     
  CacheID          string  `json:"cacheId"`         
  FormattedURL     string  `json:"formattedUrl"`    
  HTMLFormattedURL string  `json:"htmlFormattedUrl"`
  Pagemap          Pagemap `json:"pagemap"`         
}

type Pagemap struct {
  CSEThumbnail    []CSEThumbnail      `json:"cse_thumbnail"`  
  Metatags        []map[string]string `json:"metatags"`       
  CSEImage        []CSEImage          `json:"cse_image"`      
  Aggregaterating []Aggregaterating   `json:"aggregaterating"`
  Webpage         []Webpage           `json:"webpage"`        
}

type Aggregaterating struct {
  Ratingvalue string `json:"ratingvalue"`
  Bestrating  string `json:"bestrating"` 
  Ratingcount string `json:"ratingcount"`
  Reviewcount string `json:"reviewcount"`
}

type CSEImage struct {
  Src string `json:"src"`
}

type CSEThumbnail struct {
  Width  string `json:"width"` 
  Height string `json:"height"`
  Src    string `json:"src"`   
}

type Webpage struct {
  Name         string `json:"name"`        
  URL          string `json:"url"`         
  Thumbnailurl string `json:"thumbnailurl"`
  Image        string `json:"image"`       
}

type Queries struct {
  Request  []NextPage `json:"request"` 
  NextPage []NextPage `json:"nextPage"`
}

type NextPage struct {
  Title          string `json:"title"`         
  TotalResults   string `json:"totalResults"`  
  SearchTerms    string `json:"searchTerms"`   
  Count          int64  `json:"count"`         
  StartIndex     int64  `json:"startIndex"`    
  InputEncoding  string `json:"inputEncoding"` 
  OutputEncoding string `json:"outputEncoding"`
  Safe           string `json:"safe"`          
  Cx             string `json:"cx"`            
}

type SearchInformation struct {
  SearchTime            float64 `json:"searchTime"`           
  FormattedSearchTime   string  `json:"formattedSearchTime"`  
  TotalResults          string  `json:"totalResults"`         
  FormattedTotalResults string  `json:"formattedTotalResults"`
}

type URL struct {
  Type     string `json:"type"`    
  Template string `json:"template"`
}

type Kind string
const (
  CustomsearchResult Kind = "customsearch#result"
)
